### PR TITLE
change default gcc to gcc-7

### PR DESCRIPTION
**Pull request by Sameeranjoshi**

### CODE REVIEW

**Comment by apmorton** [comment]
Any background on this? Is there some issue this fixes, or are we just bumping for the sake of it?

**Comment by Sameeranjoshi** [comment]
@apmorton see [this](https://github.com/compiler-explorer/compiler-explorer/issues/1793) thread

**Comment by apmorton** [comment]
Thanks for the context.

My gut feeling is that if we are going to bump we may as well bump to the latest available in our distro (18.04 LTS), which is currently `gcc-8`

I'm also not sure if there is much difference between `gcc` and `gcc-7` on 18.04 since they are both 7.x according to the package index website.

We may also need to install the new compiler packages on our execution nodes since they may link against different glib versions or something that otherwise won't be installed.

**Comment by apmorton** [comment]
Closing this since it turned out to not be needed to get flang building

**Pull request closed without merging**
