### PR TITLE
Fix the build again

### PR DESCRIPTION
**Pull request by EricWF**
Don't be fancy, just do what everyone else does

### CODE REVIEW

**Comment by mattgodbolt** [comment]
Will give this a go

**Comment by mattgodbolt** [comment]
Looks like it's working: https://github.com/compiler-explorer/compiler-workflows/actions/runs/9893150029/job/27327568719

**Comment by mattgodbolt** [comment]
I'm afraid it failed again.

If you can: can you try running it in the docker image and check it builds OK. That way we don't have to play PR tennis :)

```
fpermissive]
2024-07-11T14:29:39.0048700Z   566 |   ContractOptions ContractOptions;
2024-07-11T14:29:39.0049335Z       |                   ^~~~~~~~~~~~~~~
2024-07-11T14:29:39.0050397Z In file included from /root/llvm-project/clang/include/clang/Basic/LangOptions.h:18,
2024-07-11T14:29:39.0051644Z                  from /root/llvm-project/clang/include/clang/AST/Type.h:28,
2024-07-11T14:29:39.0052796Z                  from /root/llvm-project/clang/include/clang/AST/CanonicalType.h:17,
2024-07-11T14:29:39.0053990Z                  from /root/llvm-project/clang/include/clang/AST/ASTContext.h:18,
2024-07-11T14:29:39.0055098Z                  from /root/llvm-project/clang/lib/Parse/ParseExpr.cpp:23:
2024-07-11T14:29:39.0056975Z /root/llvm-project/clang/include/clang/Basic/ContractOptions.h:82:7: note: 'ContractOptions' declared here as 'class clang::ContractOptions'
2024-07-11T14:29:39.0058434Z    82 | class ContractOptions {
2024-07-11T14:29:39.0058979Z       |       ^~~~~~~~~~~~~~~
2024-07-11T14:29:39.0059883Z In file included from /root/llvm-project/clang/include/clang/AST/Type.h:31,
2024-07-11T14:29:39.0061146Z                  from /root/llvm-project/clang/include/clang/AST/CanonicalType.h:17,
2024-07-11T14:29:39.0062313Z                  from /root/llvm-project/clang/include/clang/AST/ASTContext.h:18,
2024-07-11T14:29:39.0063395Z                  from /root/llvm-project/clang/lib/Parse/ParseExpr.cpp:23:
2024-07-11T14:29:39.0065677Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:61:8: warning: 'clang::PointerAuthSchema::TheKind' is too small to hold all values of 'enum class clang::PointerAuthSchema::Kind'
2024-07-11T14:29:39.0067491Z    61 |   Kind TheKind : 2;
2024-07-11T14:29:39.0067979Z       |        ^~~~~~~
2024-07-11T14:29:39.0070167Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:65:29: warning: 'clang::PointerAuthSchema::SelectedAuthenticationMode' is too small to hold all values of 'enum class clang::PointerAuthenticationMode'
2024-07-11T14:29:39.0072581Z    65 |   PointerAuthenticationMode SelectedAuthenticationMode : 2;
2024-07-11T14:29:39.0073437Z       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
2024-07-11T14:29:39.0076044Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:66:18: warning: 'clang::PointerAuthSchema::DiscriminationKind' is too small to hold all values of 'enum class clang::PointerAuthSchema::Discrimination'
2024-07-11T14:29:39.0078214Z    66 |   Discrimination DiscriminationKind : 2;
2024-07-11T14:29:39.0078899Z       |                  ^~~~~~~~~~~~~~~~~~
2024-07-11T14:29:39.0079905Z In file included from /root/llvm-project/clang/include/clang/Sema/Sema.h:58,
2024-07-11T14:29:39.0081096Z                  from /root/llvm-project/clang/include/clang/Parse/Parser.h:20,
2024-07-11T14:29:39.0082205Z                  from /root/llvm-project/clang/lib/Parse/ParseExpr.cpp:27:
2024-07-11T14:29:39.0083926Z /root/llvm-project/clang/include/clang/Sema/Scope.h: In member function 'void clang::Scope::setIsConditionVarScope(bool)':
2024-07-11T14:29:39.0086105Z /root/llvm-project/clang/include/clang/Sema/Scope.h:312:34: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
2024-07-11T14:29:39.0087605Z   312 |             (InConditionVarScope ? ConditionVarScope : 0);
2024-07-11T14:29:39.0088414Z       |              ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
2024-07-11T14:29:39.4990482Z [3452/5066] Building CXX object tools/clang/lib/Parse/CMakeFiles/obj.clangParse.dir/ParseExprCXX.cpp.o
2024-07-11T14:29:39.4991739Z FAILED: tools/clang/lib/Parse/CMakeFiles/obj.clangParse.dir/ParseExprCXX.cpp.o 
2024-07-11T14:29:39.4999865Z /opt/compiler-explorer/gcc-9.2.0/bin/g++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/root/build/tools/clang/lib/Parse -I/root/llvm-project/clang/lib/Parse -I/root/llvm-project/clang/include -I/root/build/tools/clang/include -I/root/build/include -I/root/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -MD -MT tools/clang/lib/Parse/CMakeFiles/obj.clangParse.dir/ParseExprCXX.cpp.o -MF tools/clang/lib/Parse/CMakeFiles/obj.clangParse.dir/ParseExprCXX.cpp.o.d -o tools/clang/lib/Parse/CMakeFiles/obj.clangParse.dir/ParseExprCXX.cpp.o -c /root/llvm-project/clang/lib/Parse/ParseExprCXX.cpp
2024-07-11T14:29:39.5007260Z In file included from /root/llvm-project/clang/include/clang/AST/Type.h:28,
2024-07-11T14:29:39.5008159Z                  from /root/llvm-project/clang/include/clang/AST/CanonicalType.h:17,
2024-07-11T14:29:39.5009022Z                  from /root/llvm-project/clang/include/clang/AST/ASTContext.h:18,
2024-07-11T14:29:39.5009863Z                  from /root/llvm-project/clang/lib/Parse/ParseExprCXX.cpp:12:
2024-07-11T14:29:39.5011569Z /root/llvm-project/clang/include/clang/Basic/LangOptions.h:566:19: error: declaration of 'clang::ContractOptions clang::LangOptions::ContractOptions' changes meaning of 'ContractOptions' [-fpermissive]
2024-07-11T14:29:39.5012908Z   566 |   ContractOptions ContractOptions;
2024-07-11T14:29:39.5013393Z       |                   ^~~~~~~~~~~~~~~
2024-07-11T14:29:39.5014141Z In file included from /root/llvm-project/clang/include/clang/Basic/LangOptions.h:18,
2024-07-11T14:29:39.5015024Z                  from /root/llvm-project/clang/include/clang/AST/Type.h:28,
2024-07-11T14:29:39.5015847Z                  from /root/llvm-project/clang/include/clang/AST/CanonicalType.h:17,
2024-07-11T14:29:39.5016697Z                  from /root/llvm-project/clang/include/clang/AST/ASTContext.h:18,
2024-07-11T14:29:39.5017502Z                  from /root/llvm-project/clang/lib/Parse/ParseExprCXX.cpp:12:
2024-07-11T14:29:39.5018824Z /root/llvm-project/clang/include/clang/Basic/ContractOptions.h:82:7: note: 'ContractOptions' declared here as 'class clang::ContractOptions'
2024-07-11T14:29:39.5020309Z    82 | class ContractOptions {
2024-07-11T14:29:39.5020865Z       |       ^~~~~~~~~~~~~~~
2024-07-11T14:29:39.5021525Z In file included from /root/llvm-project/clang/include/clang/AST/Type.h:31,
2024-07-11T14:29:39.5022409Z                  from /root/llvm-project/clang/include/clang/AST/CanonicalType.h:17,
2024-07-11T14:29:39.5023262Z                  from /root/llvm-project/clang/include/clang/AST/ASTContext.h:18,
2024-07-11T14:29:39.5024072Z                  from /root/llvm-project/clang/lib/Parse/ParseExprCXX.cpp:12:
2024-07-11T14:29:39.5025682Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:61:8: warning: 'clang::PointerAuthSchema::TheKind' is too small to hold all values of 'enum class clang::PointerAuthSchema::Kind'
2024-07-11T14:29:39.5026956Z    61 |   Kind TheKind : 2;
2024-07-11T14:29:39.5027338Z       |        ^~~~~~~
2024-07-11T14:29:39.5028856Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:65:29: warning: 'clang::PointerAuthSchema::SelectedAuthenticationMode' is too small to hold all values of 'enum class clang::PointerAuthenticationMode'
2024-07-11T14:29:39.5030414Z    65 |   PointerAuthenticationMode SelectedAuthenticationMode : 2;
2024-07-11T14:29:39.5031286Z       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
2024-07-11T14:29:39.5032913Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:66:18: warning: 'clang::PointerAuthSchema::DiscriminationKind' is too small to hold all values of 'enum class clang::PointerAuthSchema::Discrimination'
2024-07-11T14:29:39.5034404Z    66 |   Discrimination DiscriminationKind : 2;
2024-07-11T14:29:39.5034906Z       |                  ^~~~~~~~~~~~~~~~~~
2024-07-11T14:29:39.5035628Z In file included from /root/llvm-project/clang/include/clang/Sema/Sema.h:58,
2024-07-11T14:29:39.5036498Z                  from /root/llvm-project/clang/include/clang/Parse/Parser.h:20,
2024-07-11T14:29:39.5037312Z                  from /root/llvm-project/clang/lib/Parse/ParseExprCXX.cpp:21:
2024-07-11T14:29:39.5038523Z /root/llvm-project/clang/include/clang/Sema/Scope.h: In member function 'void clang::Scope::setIsConditionVarScope(bool)':
2024-07-11T14:29:39.5040084Z /root/llvm-project/clang/include/clang/Sema/Scope.h:312:34: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
2024-07-11T14:29:39.5041174Z   312 |             (InConditionVarScope ? ConditionVarScope : 0);
2024-07-11T14:29:39.5041767Z       |              ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
2024-07-11T14:29:40.3087210Z [3453/5066] Building CXX object tools/clang/lib/Serialization/CMakeFiles/obj.clangSerialization.dir/ASTWriterStmt.cpp.o
2024-07-11T14:29:40.3088828Z FAILED: tools/clang/lib/Serialization/CMakeFiles/obj.clangSerialization.dir/ASTWriterStmt.cpp.o 
2024-07-11T14:29:40.3097673Z /opt/compiler-explorer/gcc-9.2.0/bin/g++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/root/build/tools/clang/lib/Serialization -I/root/llvm-project/clang/lib/Serialization -I/root/llvm-project/clang/include -I/root/build/tools/clang/include -I/root/build/include -I/root/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -fno-strict-aliasing -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -MD -MT tools/clang/lib/Serialization/CMakeFiles/obj.clangSerialization.dir/ASTWriterStmt.cpp.o -MF tools/clang/lib/Serialization/CMakeFiles/obj.clangSerialization.dir/ASTWriterStmt.cpp.o.d -o tools/clang/lib/Serialization/CMakeFiles/obj.clangSerialization.dir/ASTWriterStmt.cpp.o -c /root/llvm-project/clang/lib/Serialization/ASTWriterStmt.cpp
2024-07-11T14:29:40.3105605Z In file included from /root/llvm-project/clang/include/clang/AST/Type.h:28,
2024-07-11T14:29:40.3106514Z                  from /root/llvm-project/clang/include/clang/AST/DeclarationName.h:16,
2024-07-11T14:29:40.3107380Z                  from /root/llvm-project/clang/include/clang/AST/ASTConcept.h:17,
2024-07-11T14:29:40.3108252Z                  from /root/llvm-project/clang/lib/Serialization/ASTWriterStmt.cpp:14:
2024-07-11T14:29:40.3109992Z /root/llvm-project/clang/include/clang/Basic/LangOptions.h:566:19: error: declaration of 'clang::ContractOptions clang::LangOptions::ContractOptions' changes meaning of 'ContractOptions' [-fpermissive]
2024-07-11T14:29:40.3111612Z   566 |   ContractOptions ContractOptions;
2024-07-11T14:29:40.3112089Z       |                   ^~~~~~~~~~~~~~~
2024-07-11T14:29:40.3112850Z In file included from /root/llvm-project/clang/include/clang/Basic/LangOptions.h:18,
2024-07-11T14:29:40.3113843Z                  from /root/llvm-project/clang/include/clang/AST/Type.h:28,
2024-07-11T14:29:40.3114678Z                  from /root/llvm-project/clang/include/clang/AST/DeclarationName.h:16,
2024-07-11T14:29:40.3115531Z                  from /root/llvm-project/clang/include/clang/AST/ASTConcept.h:17,
2024-07-11T14:29:40.3116384Z                  from /root/llvm-project/clang/lib/Serialization/ASTWriterStmt.cpp:14:
2024-07-11T14:29:40.3117754Z /root/llvm-project/clang/include/clang/Basic/ContractOptions.h:82:7: note: 'ContractOptions' declared here as 'class clang::ContractOptions'
2024-07-11T14:29:40.3118774Z    82 | class ContractOptions {
2024-07-11T14:29:40.3119174Z       |       ^~~~~~~~~~~~~~~
2024-07-11T14:29:40.3119819Z In file included from /root/llvm-project/clang/include/clang/AST/Type.h:31,
2024-07-11T14:29:40.3120718Z                  from /root/llvm-project/clang/include/clang/AST/DeclarationName.h:16,
2024-07-11T14:29:40.3121562Z                  from /root/llvm-project/clang/include/clang/AST/ASTConcept.h:17,
2024-07-11T14:29:40.3122421Z                  from /root/llvm-project/clang/lib/Serialization/ASTWriterStmt.cpp:14:
2024-07-11T14:29:40.3124129Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:61:8: warning: 'clang::PointerAuthSchema::TheKind' is too small to hold all values of 'enum class clang::PointerAuthSchema::Kind'
2024-07-11T14:29:40.3125392Z    61 |   Kind TheKind : 2;
2024-07-11T14:29:40.3125756Z       |        ^~~~~~~
2024-07-11T14:29:40.3127257Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:65:29: warning: 'clang::PointerAuthSchema::SelectedAuthenticationMode' is too small to hold all values of 'enum class clang::PointerAuthenticationMode'
2024-07-11T14:29:40.3128790Z    65 |   PointerAuthenticationMode SelectedAuthenticationMode : 2;
2024-07-11T14:29:40.3129406Z       |                             ^~~~~~~~~~~~~~~~~~~~~~~~~~
2024-07-11T14:29:40.3131020Z /root/llvm-project/clang/include/clang/Basic/PointerAuthOptions.h:66:18: warning: 'clang::PointerAuthSchema::DiscriminationKind' is too small to hold all values of 'enum class clang::PointerAuthSchema::Discrimination'
2024-07-11T14:29:40.3132454Z    66 |   Discrimination DiscriminationKind : 2;
2024-07-11T14:29:40.3132947Z       |                  ^~~~~~~~~~~~~~~~~~
2024-07-11T14:29:40.3133706Z In file included from /root/llvm-project/clang/include/clang/Sema/Sema.h:58,
2024-07-11T14:29:40.3134634Z                  from /root/llvm-project/clang/include/clang/Serialization/ASTReader.h:29,
2024-07-11T14:29:40.3135553Z                  from /root/llvm-project/clang/lib/Serialization/ASTWriterStmt.cpp:22:
2024-07-11T14:29:40.3136792Z /root/llvm-project/clang/include/clang/Sema/Scope.h: In member function 'void clang::Scope::setIsConditionVarScope(bool)':
2024-07-11T14:29:40.3138332Z /root/llvm-project/clang/include/clang/Sema/Scope.h:312:34: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
2024-07-11T14:29:40.3139525Z   312 |             (InConditionVarScope ? ConditionVarScope : 0);
2024-07-11T14:29:40.3140124Z       |              ~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~
2024-07-11T14:29:40.6079428Z [3454/5066] Building CXX object lib/Target/RISCV/CMakeFiles/LLVMRISCVCodeGen.dir/RISCVISelLowering.cpp.o
2024-07-11T14:29:41.8074142Z [3455/5066] Building CXX object tools/llvm-profdata/CMakeFiles/llvm-profdata.dir/llvm-profdata.cpp.o
2024-07-11T14:29:57.9423794Z [3456/5066] Building CXX object lib/Passes/CMakeFiles/LLVMPasses.dir/PassBuilder.cpp.o
2024-07-11T14:30:17.0069448Z [3457/5066] Building CXX object lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86ISelLowering.cpp.o
2024-07-11T14:31:19.0566635Z [3458/5066] Building CXX object lib/Target/AMDGPU/Disassembler/CMakeFiles/LLVMAMDGPUDisassembler.dir/AMDGPUDisassembler.cpp.o
2024-07-11T14:31:19.0567675Z ninja: build stopped: subcommand failed.
```

**Comment by EricWF** [comment]
Yeah, it seems that's needed. 

Is this blocking other nightlys (i.e. Should I send a revert?)

**Comment by partouf** [comment]
> Is this blocking other nightlys (i.e. Should I send a revert?)

No, it's no problem to keep in broken

**Pull request merged**
